version: "3.7"

services:
  database:
    image: postgres
    container_name: database_medcloud
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=med
      - POSTGRES_PASSWORD=cloud  
      - POSTGRES_DB=medcloud_db
    volumes:
      - ./pgdata:/data/postgres